version: "3.9"

services:

  # backend
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - SSH_HOST=15.188.3.237
      - SSH_USERNAME=ubuntu
      - SSH_PRIVATE_KEY_PATH=./keys/kpit-vm.pem
      - TERRAFORM_DIR=/home/ubuntu/Ansible-labs-with-Terraform
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 40s
    networks:
      - ans-labs-net
    volumes:
      - ./backend/keys/kpit-vm.pem:/app/keys/kpit-vm.pem:ro
  
  # frontend
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - REACT_APP_ANSIBLE_LAB_URL=http://15.188.3.237:2222/ssh
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ans-labs-net
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/nginx/cors.conf:/etc/nginx/cors.conf:ro
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

# networks
networks:
  ans-labs-net:
    name: ans-labs-net
    driver: bridge